export const MERMAID_KEYWORDS = [
  'graph ',
  'graph\n',
  'flowchart ',
  'flowchart\n',
  'sequenceDiagram',
  'classDiagram',
  'stateDiagram',
  'erDiagram',
  'journey',
  'gantt',
  'pie ',
  'quadrantChart',
  'requirementDiagram',
  'gitGraph',
  'mindmap',
  'timeline',
  'zenuml',
  'sankey',
  'xychart',
  'block-beta',
];
